sudo: false
language: node_js
node_js:
    - '8'
    - '10'
    - '12'
before_install:
    - npm i npminstall -g
install:
    - npminstall
script:
    - node test/setup.js
    - npm run build
    - npm run ci
after_script:
    - npminstall codecov && codecov
